WITH
--CITT AS
--(
--    select 
--        coalesce( cas.CD_ATS_APPARTENENZA, cas.CD_ATS_RESIDENZA, cas.CD_ATS_ASSISTENZA ) ATS,
--        coalesce( cas.DN_ATS_APPARTENENZA, cas.DN_ATS_RESIDENZA, cas.DN_ATS_ASSISTENZA ) DESC_ATS,
--        coalesce( cas.CD_ASST_APPARTENENZA, cas.CD_ASST_RESIDENZA, cas.CD_ASST_ASSISTENZA ) ASST,
--        coalesce( cas.DN_ASST_APPARTENENZA, cas.DN_ASST_RESIDENZA, cas.DN_ASST_ASSISTENZA ) DESC_ASST,
--        NVL( cas.ID_CENTRO_VACCINALE_APPARTENENZA, cas.ID_CENTRO_VACCINALE_PREFERENZA) CV, 
--        NVL( cas.DN_CENTRO_VACCINALE_APPARTENENZA, cas.DN_CENTRO_VACCINALE_PREFERENZA) DESC_CV, 
--        cit.CITTADINO_PK CIT_ID, 
--        cit.CD_CODICE_IDENTIFICATIVO CF, 
--        cit.CG_COGNOME COGNOME, 
--        cit.NM_NOME NOME, 
--        cit.DT_DATA_NASCITA DATA_NASCITA,
--        sta.DN_DESCRIZIONE STATO_ANAGRAFICO,  
--        DECODE( NVL( cit.CD_NAR, 'Locale' ), 'Locale', 'Locale', 'Locale+Centrale') TIPO_ANAGRAFICA, 
--        med.CD_CODICE_FISCALE CF_PEDIATRA, 
--        med.CG_COGNOME || ' ' || med.NM_NOME PEDIATRA, 
--        cit.ID_COMUNE_RESIDENZA, 
--        comR.DN_NOME COMUNE_RESIDENZA, 
--        cit.ID_COMUNE_DOMICILIO, 
--        comD.DN_NOME COMUNE_DOMICILIO
--    from 
--        arvax_usermgr.cittadino cit
--        left join ARVAX_USERMGR.LOCALITA comR on ( comR.LOCALITA_PK = cit.ID_COMUNE_RESIDENZA and comR.DT_FINE_VALIDITA is null and nvl( comR.FL_OBSOLETO, '0' ) = '0' )
--        left join ARVAX_USERMGR.LOCALITA comD on ( comD.LOCALITA_PK = cit.ID_COMUNE_DOMICILIO and comD.DT_FINE_VALIDITA is null and nvl( comD.FL_OBSOLETO, '0' ) = '0' )
--        left join ARVAX_USERMGR.CITTADINO_ASSISTENZA_SANITARIA cas on ( cas.ID_CITTADINO = cit.CITTADINO_PK )
--        left join ARVAX_USERMGR.STATO_ANAGRAFICA sta ON ( sta.STATO_ANAGRAFICA_PK = cit.ID_STATO_ANAGRAFICA and sta.FL_CESSATO = 0 )
--        left join ARVAX_USERMGR.MEDICO med ON ( med.MEDICO_PK = cas.ID_MEDICO AND cas.DT_DATA_FINE_MEDICO IS NULL )
--    where 1=1 
--    --and cit.DT_DATA_NASCITA >= to_date( '01/01/2025', 'dd/mm/yyyy' )
--    --and cit.DT_DATA_DECESSO is null
--    and nvl( cit.FL_MERGE, '0') = '0'
--)
--,
NOMI_COMM AS
(
    SELECT 
        nce.NOME_COMMERCIALE_PK NC_PK, 
        COALESCE(ncb.DN_DESCRIZIONE, nce.DN_DESCRIZIONE) AS NC_DES
    FROM ARVAX_APPROVVIGIONAMENTO.NOME_COMMERCIALE nce
    LEFT JOIN ARVAX_APPROVVIGIONAMENTO.NOME_COMMERCIALE ncb ON nce.ID_NOME_COMMERCIALE_BREVE = ncb.NOME_COMMERCIALE_PK
)
,
VACC AS
(
    SELECT distinct
        citt.CITTADINO_PK, 
        citt.CD_CODICE_IDENTIFICATIVO CF, 
        citt.DT_DATA_NASCITA DATA_NASCITA, 
        '030' || ats.CD_CODICE_ESTERNO CD_ATS, 
        ats.DN_DESCRIZIONE DS_ATS, 
        asst.CD_CODICE CD_ASST, 
        asst.DN_DESCRIZIONE DS_ASST, 
        vcc.CD_CENTRO_VACCINALE, 
        vcc.DN_CENTRO_VACCINALE, 
        tcns.DN_SIGLA AS TIPO_CV,
        lcns.DN_SIGLA_PROVINCIA PROV_CV,
        vcc.CD_ASSOCIAZIONE_VACCINALE,
        vcc.DN_ASSOCIAZIONE_VACCINALE, 
        --cva.CD_VACCINAZIONE, 
        vax.DN_DESCRIZIONE AS TIPO_VACCINO,
        vcc.NR_VACCINO_DOSE,
        vcc.TM_SOMMINISTRAZIONE, 
        CASE WHEN vcc.CD_TIPO = 'E' THEN 'Eseguita' ELSE 'Registrata' END AS TIPO, 
        CASE WHEN vcc.CD_TIPO <> 'E' AND NOMI_COMM.NC_DES IS NULL THEN 'farmaco mancante' ELSE NOMI_COMM.NC_DES END AS NOME_COMMERCIALE_BREVE, 
        CASE WHEN NVL(som.FL_PAGAMENTO, 0) = 0 THEN 'No' ELSE 'Si' END A_PAGAMENTO, 
        CASE WHEN NVL(vsm.FL_DOMICILIO, 0) = 0 THEN 'No' ELSE 'Si' END A_DOMICILIO, 
        CASE WHEN NVL(vint.FL_INTERNAZIONALE, 0) = 0 THEN 'No' ELSE 'Si' END VIAGG_INTERNAZ, 
        cris.DN_DESCRIZIONE_BREVE CATEG_RISCHIO,
        CASE WHEN NVL(vanr.FL_RISPOSTA, 0) = 0 THEN 'No' ELSE 'Si' END IN_GRAVIDANZA        
    FROM 
        ARVAX_USERMGR.cittadino citt
        INNER JOIN ARVAX_USERMGR.CITTADINO_VACCINAZIONE vcc ON vcc.ID_CITTADINO = CITT.CITTADINO_PK
        INNER JOIN ARVAX_USERMGR.CITTADINO_VACCINAZIONE_ANTIGENE cva ON ( cva.ID_CITTADINO_VACCINAZIONE = vcc.CITTADINO_VACCINAZIONE_PK )
        INNER JOIN ARVAX_PROGRAMMAZIONE.CENTRO_VACCINALE cns ON cns.CENTRO_VACCINALE_PK = vcc.ID_CENTRO_VACCINALE
        INNER JOIN ARVAX_PROGRAMMAZIONE.TIPO_CENTRO_VACCINALE tcns ON tcns.TIPO_CENTRO_VACCINALE_PK = cns.ID_TIPO_CENTRO_VACCINALE 
        LEFT JOIN  ARVAX_PROGRAMMAZIONE.V_LOCALITA_RD lcns ON lcns.LOCALITA_PK = cns.ID_COMUNE  
        INNER JOIN ARVAX_PROGRAMMAZIONE.ATS ats ON ats.ATS_PK = cns.ID_ATS        
        INNER JOIN ARVAX_PROGRAMMAZIONE.ASST asst ON ( asst.ASST_PK = cns.ID_ASST and asst.ID_ATS = ats.ATS_PK )
        INNER JOIN ARVAX_PROGRAMMAZIONE.ASS_VACCINO_ASSOCIAZIONE_VACCINALE avav ON avav.ID_ASSOCIAZIONE_VACCINALE = vcc.ID_ASSOCIAZIONE_VACCINALE
        INNER JOIN ARVAX_PROGRAMMAZIONE.VACCINO vax ON vax.VACCINO_PK = avav.ID_VACCINO
        LEFT JOIN ARVAX_SOMMINISTRAZIONE.VACCINAZIONE_SOMMINISTRAZIONE vsm ON vsm.VACCINAZIONE_SOMMINISTRAZIONE_PK = vcc.ID_VACCINAZIONE_SOMMINISTRAZIONE
        LEFT JOIN NOMI_COMM ON 
        (
            NOMI_COMM.NC_PK =   CASE
                                WHEN vcc.CD_TIPO = 'E' THEN vsm.ID_NOME_COMMERCIALE
                                ELSE vcc.ID_LOTTO_NOME_COMMERCIALE 
                                END
        )
        LEFT JOIN ARVAX_APPROVVIGIONAMENTO.SOMMINISTRAZIONE som ON som.ID_SOMMINISTRAZIONE_VACCINO = vsm.VACCINAZIONE_SOMMINISTRAZIONE_PK
        LEFT JOIN
        (
            select 
                vac2.ID_CITTADINO, 
                1 FL_INTERNAZIONALE
            from 
                ARVAX_SOMMINISTRAZIONE.VACCINAZIONE vac2
                INNER JOIN ARVAX_SOMMINISTRAZIONE.VACCINAZIONE_SOMMINISTRAZIONE som2 ON (som2.ID_VACCINAZIONE = vac2.VACCINAZIONE_PK  )
            where 1=1
            and ( nvl(vac2.FL_COUNSELING, 0) = 1 OR nvl(som2.FL_COUNSELING, 0) = 1 )
            and nvl(FL_ACCETTAZIONE, 0 ) = 1
            and som2.TM_FINE_VALIDITA is null
        ) vint
        ON vint.ID_CITTADINO = CITT.CITTADINO_PK
        LEFT JOIN ARVAX_SOMMINISTRAZIONE.VACCINAZIONE_ANAMNESI vanm on vanm.VACCINAZIONE_ANAMNESI_PK = vcc.ID_ANAMNESI
        LEFT JOIN ARVAX_SOMMINISTRAZIONE.VACCINAZIONE_ANAMNESI_RISPOSTA vanr ON (vanr.ID_VACCINAZIONE_ANAMNESI = vcc.ID_ANAMNESI and NVL(vanr.ID_DOMANDA_ANAMNESI,  '11-1') = '11-1' )
        LEFT JOIN ARVAX_USERMGR.CATEGORIA_RISCHIO cris on cris.CATEGORIA_RISCHIO_PK = vanm.CD_CATEGORIA_RISCHIO        
where 1=1 
    AND nvl( citt.FL_MERGE, '0') = '0'
    AND ( citt.DT_DATA_DECESSO is null OR citt.DT_DATA_DECESSO >= vcc.DT_SOMMINISTRAZIONE )
    AND NVL(vcc.FL_DELETE,'0') = '0'
    AND vcc.FL_CONSENSO = '1'
    AND vcc.FL_IDONEITA = '1'
    and vcc.DT_SOMMINISTRAZIONE between to_date( '01/06/2025', 'dd/mm/yyyy' ) and to_date( '30/09/2025', 'dd/mm/yyyy' )
    AND vcc.DN_CREATO_DA not in ('Migrazione', 'Poste', 'Ministero')
    AND vcc.DN_MODIFICATO_DA not in ('Migrazione', 'Poste', 'Ministero')
    --AND NVL(vsm.FL_DELETE, 0) = 0
)
select 
    --VACC.CD_ATS, 
    VACC.DS_ATS, 
    --VACC.CD_ASST, 
    VACC.DS_ASST, 
    VACC.CF, 
    VACC.CD_CENTRO_VACCINALE, 
    VACC.TIPO_CV, 
    VACC.DN_CENTRO_VACCINALE,     
    VACC.PROV_CV, 
    VACC.TIPO_VACCINO,
    VACC.NR_VACCINO_DOSE,
    to_char( VACC.TM_SOMMINISTRAZIONE, 'dd/mm/yyyy HH24:mi:ss') DATA_ORA_SOMMINISTRAZIONE, 
    VACC.TIPO,
    VACC.NOME_COMMERCIALE_BREVE, 
    VACC.A_PAGAMENTO, 
    VACC.A_DOMICILIO,
    VACC.VIAGG_INTERNAZ, 
    VACC.CATEG_RISCHIO, 
    VACC.IN_GRAVIDANZA, 
    FLOOR(MONTHS_BETWEEN(VACC.TM_SOMMINISTRAZIONE, VACC.DATA_NASCITA)/12) AS ETA_ALLA_SOMMINISTRAZIONE
from 
    VACC
Where 1=1 
    AND VACC.CD_ATS = '030321'
    --AND VACC.CD_CENTRO_VACCINALE = '32170352'
order by 
    VACC.DS_ATS, 
    VACC.DS_ASST, 
    VACC.CD_CENTRO_VACCINALE, 
    VACC.CF, 
    VACC.TM_SOMMINISTRAZIONE 

--
--    CITT.ATS, 
--    CITT.ASST, 
; 
